services:
  app:
    build: .
    container_name: divar-alert
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_API_URL=https://tapi.bale.ai
      - DB_PATH=./db.badger
    volumes:
      - ./db.badger:/db.badger