services:
  app:
    build: .
    container_name: divar-alert-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_API_URL=https://tapi.bale.ai
      - DB_PATH=/root/app/db.badger
    volumes:
      - ./db.badger:/root/app/db.badger